//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscaRangoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_Avaliacao_Estabelecimento
    {
        public int Id_Estabelecimento { get; set; }
        public int Id_Usuario { get; set; }
        public int Id_Caracteristica { get; set; }
        public int Nota { get; set; }
    
        public virtual BR_Caracteristica_Estabelecimento BR_Caracteristica_Estabelecimento { get; set; }
        public virtual BR_Estabelecimento BR_Estabelecimento { get; set; }
        public virtual BR_Usuario BR_Usuario { get; set; }
    }
}
