//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscaRangoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_Curtir_Prato_Personalizado
    {
        public int Id_Prato { get; set; }
        public int Id_Usuario { get; set; }
        public bool Positivo { get; set; }
    
        public virtual BR_Prato_Personalizado BR_Prato_Personalizado { get; set; }
        public virtual BR_Usuario BR_Usuario { get; set; }
    }
}
