//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscaRangoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_Chamada_Garcom
    {
        public int Id { get; set; }
        public int Id_Tipo { get; set; }
        public int Id_Usuario { get; set; }
        public int Id_Estabelecimento { get; set; }
        public int Num_Mesa { get; set; }
    
        public virtual BR_Estabelecimento BR_Estabelecimento { get; set; }
        public virtual BR_Tipo_Chamada BR_Tipo_Chamada { get; set; }
        public virtual BR_Usuario BR_Usuario { get; set; }
    }
}
