//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscaRangoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_Cidade
    {
        public BR_Cidade()
        {
            this.BR_Bairro = new HashSet<BR_Bairro>();
        }
    
        public int Id { get; set; }
        public int Id_Estado { get; set; }
        public string Cidade { get; set; }
    
        public virtual ICollection<BR_Bairro> BR_Bairro { get; set; }
        public virtual BR_Estado BR_Estado { get; set; }
    }
}
