//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscaRangoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_Denuncia
    {
        public int Id { get; set; }
        public bool Esta_Resolvido { get; set; }
        public string Entidade { get; set; }
        public int Id_Entidade { get; set; }
        public int Id_Usuario { get; set; }
    
        public virtual BR_Usuario BR_Usuario { get; set; }
    }
}
