
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BuscaRangoCode
{

using System;
    using System.Collections.Generic;
    
public partial class BR_Estado
{

    public BR_Estado()
    {

        this.BR_Cidade = new HashSet<BR_Cidade>();

    }


    public int Id { get; set; }

    public int Id_Pais { get; set; }

    public string Estado { get; set; }



    public virtual ICollection<BR_Cidade> BR_Cidade { get; set; }

    public virtual BR_Pais BR_Pais { get; set; }

}

}
