//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscaRangoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_Estabelecimento
    {
        public BR_Estabelecimento()
        {
            this.BR_Avaliacao_Estabelecimento = new HashSet<BR_Avaliacao_Estabelecimento>();
            this.BR_Chamada_Garcom = new HashSet<BR_Chamada_Garcom>();
            this.BR_Comentario_Estabelecimento = new HashSet<BR_Comentario_Estabelecimento>();
            this.BR_Fotos_Estabelecimento = new HashSet<BR_Fotos_Estabelecimento>();
            this.BR_Ingrediente_Personalizado = new HashSet<BR_Ingrediente_Personalizado>();
            this.BR_Permissao_Chamada = new HashSet<BR_Permissao_Chamada>();
            this.BR_Prato_Personalizado = new HashSet<BR_Prato_Personalizado>();
            this.BR_Referencias_Estabelecimento = new HashSet<BR_Referencias_Estabelecimento>();
            this.BR_Lista_Estabelecimento = new HashSet<BR_Lista_Estabelecimento>();
            this.BR_Formas_Pagamento = new HashSet<BR_Formas_Pagamento>();
            this.BR_Tag = new HashSet<BR_Tag>();
        }
    
        public int Id { get; set; }
        public int Id_Bairro { get; set; }
        public string Razao_Social { get; set; }
        public string Tel_Responsavel { get; set; }
        public string Email_Responsavel { get; set; }
        public string Email { get; set; }
        public string CNPJ { get; set; }
        public Nullable<int> Status { get; set; }
        public int Capacidade_Max { get; set; }
        public string Tel_Contato { get; set; }
        public string Tel_Entrega { get; set; }
        public string Endereco { get; set; }
        public string Numero_Endereco { get; set; }
        public string CEP { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Descricao_Curta { get; set; }
        public string Descricao { get; set; }
        public bool Tem_Customizacao { get; set; }
        public bool Tem_Chamada_Garcom { get; set; }
        public bool Tem_Estacionamento { get; set; }
        public bool Tem_Musica { get; set; }
        public bool Tem_Acesso_Deficiente { get; set; }
        public bool Tem_Reserva { get; set; }
        public bool Tem_Fraldario { get; set; }
        public bool Tem_Wifi { get; set; }
        public bool Tem_Espaco_Kids { get; set; }
        public bool Ativo { get; set; }
        public bool Abre_Segunda { get; set; }
        public bool Abre_Sabado { get; set; }
        public bool Abre_Domingo { get; set; }
        public string Hora_Normal_Inicio { get; set; }
        public string Hora_Normal_Fim { get; set; }
        public string Hora_Sabado_Inicio { get; set; }
        public string Hora_Sabado_Fim { get; set; }
        public string Hora_Domingo_Inicio { get; set; }
        public string Hora_Domingo_Fim { get; set; }
    
        public virtual ICollection<BR_Avaliacao_Estabelecimento> BR_Avaliacao_Estabelecimento { get; set; }
        public virtual BR_Bairro BR_Bairro { get; set; }
        public virtual ICollection<BR_Chamada_Garcom> BR_Chamada_Garcom { get; set; }
        public virtual ICollection<BR_Comentario_Estabelecimento> BR_Comentario_Estabelecimento { get; set; }
        public virtual ICollection<BR_Fotos_Estabelecimento> BR_Fotos_Estabelecimento { get; set; }
        public virtual ICollection<BR_Ingrediente_Personalizado> BR_Ingrediente_Personalizado { get; set; }
        public virtual ICollection<BR_Permissao_Chamada> BR_Permissao_Chamada { get; set; }
        public virtual ICollection<BR_Prato_Personalizado> BR_Prato_Personalizado { get; set; }
        public virtual ICollection<BR_Referencias_Estabelecimento> BR_Referencias_Estabelecimento { get; set; }
        public virtual ICollection<BR_Lista_Estabelecimento> BR_Lista_Estabelecimento { get; set; }
        public virtual ICollection<BR_Formas_Pagamento> BR_Formas_Pagamento { get; set; }
        public virtual ICollection<BR_Tag> BR_Tag { get; set; }
    }
}
