
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BuscaRangoCode
{

using System;
    using System.Collections.Generic;
    
public partial class BR_Ingrediente
{

    public BR_Ingrediente()
    {

        this.BR_Ingrediente_Personalizado = new HashSet<BR_Ingrediente_Personalizado>();

        this.BR_Prato_Personalizado = new HashSet<BR_Prato_Personalizado>();

    }


    public int Id { get; set; }

    public string Nome { get; set; }



    public virtual ICollection<BR_Ingrediente_Personalizado> BR_Ingrediente_Personalizado { get; set; }

    public virtual ICollection<BR_Prato_Personalizado> BR_Prato_Personalizado { get; set; }

}

}
