//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscaRangoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_Ingrediente_Personalizado
    {
        public int Id { get; set; }
        public int Id_Ingrediente { get; set; }
        public int Id_Estabelecimento { get; set; }
        public int Grupo { get; set; }
        public double Preco { get; set; }
    
        public virtual BR_Estabelecimento BR_Estabelecimento { get; set; }
        public virtual BR_Ingrediente BR_Ingrediente { get; set; }
    }
}
