
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BuscaRangoCode
{

using System;
    using System.Collections.Generic;
    
public partial class BR_Lista_Estabelecimento
{

    public BR_Lista_Estabelecimento()
    {

        this.BR_Estabelecimento = new HashSet<BR_Estabelecimento>();

    }


    public int Id { get; set; }

    public int Id_Usuario { get; set; }

    public string Nome_Lista { get; set; }



    public virtual BR_Usuario BR_Usuario { get; set; }

    public virtual ICollection<BR_Estabelecimento> BR_Estabelecimento { get; set; }

}

}
