//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscaRangoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_Prato_Personalizado
    {
        public BR_Prato_Personalizado()
        {
            this.BR_Curtir_Prato_Personalizado = new HashSet<BR_Curtir_Prato_Personalizado>();
            this.BR_Ingrediente = new HashSet<BR_Ingrediente>();
        }
    
        public int Id { get; set; }
        public int Id_Usuario { get; set; }
        public int Id_Estabelecimento { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<BR_Curtir_Prato_Personalizado> BR_Curtir_Prato_Personalizado { get; set; }
        public virtual BR_Estabelecimento BR_Estabelecimento { get; set; }
        public virtual BR_Usuario BR_Usuario { get; set; }
        public virtual ICollection<BR_Ingrediente> BR_Ingrediente { get; set; }
    }
}
