
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BuscaRangoCode
{

using System;
    using System.Collections.Generic;
    
public partial class BR_Prato
{

    public BR_Prato()
    {

        this.BR_Avaliacao_Prato = new HashSet<BR_Avaliacao_Prato>();

        this.BR_Comentario_Prato = new HashSet<BR_Comentario_Prato>();

        this.BR_Log_Prato = new HashSet<BR_Log_Prato>();

        this.BR_Lista_Prato = new HashSet<BR_Lista_Prato>();

        this.BR_Tag = new HashSet<BR_Tag>();

    }


    public int Id { get; set; }

    public string Nome { get; set; }

    public string Descricao { get; set; }

    public string Descricao_Curta { get; set; }

    public double Preco { get; set; }

    public bool Tem_Entrega { get; set; }

    public bool Ativo { get; set; }

    public string Imagem { get; set; }

    public int Id_Estabelecimento { get; set; }



    public virtual ICollection<BR_Avaliacao_Prato> BR_Avaliacao_Prato { get; set; }

    public virtual ICollection<BR_Comentario_Prato> BR_Comentario_Prato { get; set; }

    public virtual ICollection<BR_Log_Prato> BR_Log_Prato { get; set; }

    public virtual ICollection<BR_Lista_Prato> BR_Lista_Prato { get; set; }

    public virtual ICollection<BR_Tag> BR_Tag { get; set; }

    public virtual BR_Estabelecimento BR_Estabelecimento { get; set; }

}

}
