//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscaRangoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_Pais
    {
        public BR_Pais()
        {
            this.BR_Estado = new HashSet<BR_Estado>();
        }
    
        public int Id { get; set; }
        public string Pais { get; set; }
    
        public virtual ICollection<BR_Estado> BR_Estado { get; set; }
    }
}
