
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BuscaRangoCode
{

using System;
    using System.Collections.Generic;
    
public partial class BR_Tipo_Chamada
{

    public BR_Tipo_Chamada()
    {

        this.BR_Chamada_Garcom = new HashSet<BR_Chamada_Garcom>();

    }


    public int Id { get; set; }

    public string Tipo { get; set; }



    public virtual ICollection<BR_Chamada_Garcom> BR_Chamada_Garcom { get; set; }

}

}
