//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscaRangoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_Tag
    {
        public BR_Tag()
        {
            this.BR_Estabelecimento = new HashSet<BR_Estabelecimento>();
            this.BR_Prato = new HashSet<BR_Prato>();
        }
    
        public int Id { get; set; }
        public string Tag { get; set; }
    
        public virtual ICollection<BR_Estabelecimento> BR_Estabelecimento { get; set; }
        public virtual ICollection<BR_Prato> BR_Prato { get; set; }
    }
}
