
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BuscaRangoCode
{

using System;
    using System.Collections.Generic;
    
public partial class BR_Usuario
{

    public BR_Usuario()
    {

        this.BR_Avaliacao_Estabelecimento = new HashSet<BR_Avaliacao_Estabelecimento>();

        this.BR_Avaliacao_Prato = new HashSet<BR_Avaliacao_Prato>();

        this.BR_Chamada_Garcom = new HashSet<BR_Chamada_Garcom>();

        this.BR_Comentario_Estabelecimento = new HashSet<BR_Comentario_Estabelecimento>();

        this.BR_Comentario_Prato = new HashSet<BR_Comentario_Prato>();

        this.BR_Curtir_Comentario_Estabelecimento = new HashSet<BR_Curtir_Comentario_Estabelecimento>();

        this.BR_Curtir_Comentario_Prato = new HashSet<BR_Curtir_Comentario_Prato>();

        this.BR_Curtir_Prato_Personalizado = new HashSet<BR_Curtir_Prato_Personalizado>();

        this.BR_Denuncia = new HashSet<BR_Denuncia>();

        this.BR_Lista_Estabelecimento = new HashSet<BR_Lista_Estabelecimento>();

        this.BR_Lista_Prato = new HashSet<BR_Lista_Prato>();

        this.BR_Log_Prato = new HashSet<BR_Log_Prato>();

        this.BR_Permissao_Chamada = new HashSet<BR_Permissao_Chamada>();

        this.BR_Prato_Personalizado = new HashSet<BR_Prato_Personalizado>();

    }


    public int Id { get; set; }

    public string Nome { get; set; }

    public string Email { get; set; }

    public string Senha { get; set; }

    public string Token { get; set; }

    public string Secret { get; set; }

    public string Foto { get; set; }



    public virtual ICollection<BR_Avaliacao_Estabelecimento> BR_Avaliacao_Estabelecimento { get; set; }

    public virtual ICollection<BR_Avaliacao_Prato> BR_Avaliacao_Prato { get; set; }

    public virtual ICollection<BR_Chamada_Garcom> BR_Chamada_Garcom { get; set; }

    public virtual ICollection<BR_Comentario_Estabelecimento> BR_Comentario_Estabelecimento { get; set; }

    public virtual ICollection<BR_Comentario_Prato> BR_Comentario_Prato { get; set; }

    public virtual ICollection<BR_Curtir_Comentario_Estabelecimento> BR_Curtir_Comentario_Estabelecimento { get; set; }

    public virtual ICollection<BR_Curtir_Comentario_Prato> BR_Curtir_Comentario_Prato { get; set; }

    public virtual ICollection<BR_Curtir_Prato_Personalizado> BR_Curtir_Prato_Personalizado { get; set; }

    public virtual ICollection<BR_Denuncia> BR_Denuncia { get; set; }

    public virtual ICollection<BR_Lista_Estabelecimento> BR_Lista_Estabelecimento { get; set; }

    public virtual ICollection<BR_Lista_Prato> BR_Lista_Prato { get; set; }

    public virtual ICollection<BR_Log_Prato> BR_Log_Prato { get; set; }

    public virtual ICollection<BR_Permissao_Chamada> BR_Permissao_Chamada { get; set; }

    public virtual ICollection<BR_Prato_Personalizado> BR_Prato_Personalizado { get; set; }

}

}
