//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscaRangoCode
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ER_Entities : DbContext
    {
        public ER_Entities()
            : base("name=ER_Entities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BR_Avaliacao_Estabelecimento> BR_Avaliacao_Estabelecimento { get; set; }
        public virtual DbSet<BR_Avaliacao_Prato> BR_Avaliacao_Prato { get; set; }
        public virtual DbSet<BR_Bairro> BR_Bairro { get; set; }
        public virtual DbSet<BR_Caracteristica_Estabelecimento> BR_Caracteristica_Estabelecimento { get; set; }
        public virtual DbSet<BR_Caracteristica_Prato> BR_Caracteristica_Prato { get; set; }
        public virtual DbSet<BR_Chamada_Garcom> BR_Chamada_Garcom { get; set; }
        public virtual DbSet<BR_Cidade> BR_Cidade { get; set; }
        public virtual DbSet<BR_Comentario_Estabelecimento> BR_Comentario_Estabelecimento { get; set; }
        public virtual DbSet<BR_Comentario_Prato> BR_Comentario_Prato { get; set; }
        public virtual DbSet<BR_Curtir_Comentario_Estabelecimento> BR_Curtir_Comentario_Estabelecimento { get; set; }
        public virtual DbSet<BR_Curtir_Comentario_Prato> BR_Curtir_Comentario_Prato { get; set; }
        public virtual DbSet<BR_Curtir_Prato_Personalizado> BR_Curtir_Prato_Personalizado { get; set; }
        public virtual DbSet<BR_Denuncia> BR_Denuncia { get; set; }
        public virtual DbSet<BR_Estabelecimento> BR_Estabelecimento { get; set; }
        public virtual DbSet<BR_Estado> BR_Estado { get; set; }
        public virtual DbSet<BR_Formas_Pagamento> BR_Formas_Pagamento { get; set; }
        public virtual DbSet<BR_Fotos_Estabelecimento> BR_Fotos_Estabelecimento { get; set; }
        public virtual DbSet<BR_Ingrediente> BR_Ingrediente { get; set; }
        public virtual DbSet<BR_Ingrediente_Personalizado> BR_Ingrediente_Personalizado { get; set; }
        public virtual DbSet<BR_Lista_Estabelecimento> BR_Lista_Estabelecimento { get; set; }
        public virtual DbSet<BR_Lista_Prato> BR_Lista_Prato { get; set; }
        public virtual DbSet<BR_Log_Prato> BR_Log_Prato { get; set; }
        public virtual DbSet<BR_Pais> BR_Pais { get; set; }
        public virtual DbSet<BR_Permissao_Chamada> BR_Permissao_Chamada { get; set; }
        public virtual DbSet<BR_Prato> BR_Prato { get; set; }
        public virtual DbSet<BR_Prato_Personalizado> BR_Prato_Personalizado { get; set; }
        public virtual DbSet<BR_Referencias_Estabelecimento> BR_Referencias_Estabelecimento { get; set; }
        public virtual DbSet<BR_Tag> BR_Tag { get; set; }
        public virtual DbSet<BR_Tipo_Chamada> BR_Tipo_Chamada { get; set; }
        public virtual DbSet<BR_Usuario> BR_Usuario { get; set; }
    }
}
